### ISSUE TITLE
AttributeError: 'module' object has no attribute 'states'

### ISSUE THREAD

**Issue by sulgik** [mattjj/pyhsmm-factorial#7]
Hi, 

I followed the direction in readme of factorial, and got this error code. 

Traceback (most recent call last):
  File "pyhsmm/plugins/factorial/example.py", line 9, in <module>
    import models
  File "/home/sulgik/pyhsmm/plugins/factorial/models.py", line 6, in <module>
    from internals.states import FactorialStates,\
  File "/home/sulgik/pyhsmm/plugins/factorial/internals/states.py", line 151, in <module>
    class FactorialComponentHSMMStates(pyhsmm.internals.states.HSMMStatesPython):
AttributeError: 'module' object has no attribute 'states' 

Can you give me any sort of clues that I can try for this?

**Comment by mattjj** [comment]
I haven't touched the factorial code in a long time, and it only works with a specific commit of pyhsmm (specified in the readme). It looks like you might not be on that pyhsmm commit.

**Comment by mattjj** [comment]
Check these two things:
1. Start a python interpreter and type `import pyhsmm; print pyhsmm.__file__`
2. Check the pyhsmm commit by going to the directory printed in step 1 and doing `git rev-parse --short HEAD`

**Comment by sulgik** [comment]
Thanks for the response. I got this message:

> > import pyhsmm; print pyhsmm.file
> > Traceback (most recent call last):
> >   File "<stdin>", line 1, in <module>
> > AttributeError: 'module' object has no attribute 'file'

**Comment by mattjj** [comment]
Sorry, I was typing on a phone and Github formatted the text funny. You need to check `pyhsmm.__file__`, which every Python module keeps as a reference to its corresponding .pyc filename.

**Comment by akkou** [comment]
Thanks. I am going to try older version of pyhsmm.
Can you give me any hint about which version I should check first?

**Comment by sulgik** [comment]
Hi 

I had a clue from a closed issue ( https://github.com/mattjj/pyhsmm-factorial/issues/3 ) and tried this

> git checkout af79471
> git clone -b working-factorial https://github.com/mattjj/pyhsmm.git
> cd pyhsmm
> git submodule update --init --recursive

Now, I have this message:

Submodule 'basic/pybasicbayes' (git://github.com/mattjj/pybasicbayes.git) registered for path 'basic/pybasicbayes'
Submodule 'deps/Eigen3' (git://github.com/mattjj/Eigen3.git) registered for path 'deps/Eigen3'
Submodule 'util' (git://github.com/mattjj/pymattutil.git) registered for path 'util'
Cloning into 'basic/pybasicbayes'...
remote: Counting objects: 2429, done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 2429 (delta 4), reused 0 (delta 0), pack-reused 2413
Receiving objects: 100% (2429/2429), 740.95 KiB | 275.00 KiB/s, done.
Resolving deltas: 100% (1523/1523), done.
Checking connectivity... done.
Submodule path 'basic/pybasicbayes': checked out '0de63a91ec0e4df446173f8fbed76ca2b45e6ee9'
Submodule 'util' (git://github.com/mattjj/pymattutil.git) registered for path 'util'
Cloning into 'util'...
remote: Counting objects: 365, done.
remote: Total 365 (delta 0), reused 0 (delta 0), pack-reused 365
Receiving objects: 100% (365/365), 61.73 KiB | 0 bytes/s, done.
Resolving deltas: 100% (212/212), done.
Checking connectivity... done.
Submodule path 'basic/pybasicbayes/util': checked out 'f24b19e9f56377cfceadc3b62b9124a940cce4fc'
Cloning into 'deps/Eigen3'...
fatal: remote error:
  Repository not found.
Clone of 'git://github.com/mattjj/Eigen3.git' into submodule path 'deps/Eigen3' failed

**Comment by mattjj** [comment]
Are you on the working-factorial branch of pyhsmm? That commit should work, but if it's not (and you checked that you're on the right one) then I don't have any guidance. It's unlikely that I'll get a chance to look into it any time in the near future.

**Comment by mattjj** [comment]
Sorry, disregard my last message (now deleted).

Oh yeah, I did delete my Eigen repository. I forgot it would cause problems here!

Just download [Eigen](http://eigen.tuxfamily.org/index.php?title=Main_Page) and put it in deps (you may need to rename it to Eigen3 or something, but once you get the path right it should compile). This is progress!

**Comment by sulgik** [comment]
Many thanks Matthew, 

> git clone -b working-factorial https://github.com/mattjj/pyhsmm.git
> cd pyhsmm

Since util directory was empty, so I filled from https://github.com/mattjj/pymattutil/tree/ddf6383091cb55006c36edd33edf166ba3ddcf93. 

> git submodule update --init --recursive

Then, I filled dep/Eigen3 directory as Matthew directed.

> git clone https://github.com/mattjj/pyhsmm-factorial.git ./plugins/factorial

Now, it seems to work. (At least no warning message)

**Comment by mattjj** [comment]
I'm glad you got it working and that you documented your fix! I'll leave this issue open until I can update the readme with better instructions. Thanks!

**Comment by tamlhp** [comment]
Hello, I followed the last guide of akkou but still got an error:

File "pyhsmm/internals/transitions.py", line 9, in <module>
    from ..basic.distributions import DirGamma

I am wondering where I can find the DirGamma.

Thanks and Best Regards,
Tam

**Comment by mattjj** [comment]
This code likely needs an older version of pybasicbayes. You could try cloning the repo and checking out an old version based on the date when this pyhsmm-factorial code was last updated.

Unfortunately I'm not currently working on this code and I won't have the spare cycles to fix it in the near future. However, if you make progress, let us know here (or make a PR)!
